/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as CriarContaRouteImport } from './routes/criar-conta'
import { Route as CronologiaRouteImport } from './routes/cronologia'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as NovaRouteImport } from './routes/nova'
import { Route as MedidaIdRouteImport } from './routes/medida.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const CronologiaRoute = CronologiaRouteImport.update({
  id: '/cronologia',
  path: '/cronologia',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaRoute = NovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const MedidaIdRoute = MedidaIdRouteImport.update({
  id: '/medida/$id',
  path: '/medida/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/criar-conta': typeof CriarContaRoute
  '/cronologia': typeof CronologiaRoute
  '/entrar': typeof EntrarRoute
  '/nova': typeof NovaRoute
  '/medida/$id': typeof MedidaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/criar-conta': typeof CriarContaRoute
  '/cronologia': typeof CronologiaRoute
  '/entrar': typeof EntrarRoute
  '/nova': typeof NovaRoute
  '/medida/$id': typeof MedidaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/checkout': typeof CheckoutRoute
  '/conta': typeof ContaRoute
  '/criar-conta': typeof CriarContaRoute
  '/cronologia': typeof CronologiaRoute
  '/entrar': typeof EntrarRoute
  '/nova': typeof NovaRoute
  '/medida/$id': typeof MedidaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/checkout'
    | '/conta'
    | '/criar-conta'
    | '/cronologia'
    | '/entrar'
    | '/nova'
    | '/medida/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/checkout'
    | '/conta'
    | '/criar-conta'
    | '/cronologia'
    | '/entrar'
    | '/nova'
    | '/medida/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/checkout'
    | '/conta'
    | '/criar-conta'
    | '/cronologia'
    | '/entrar'
    | '/nova'
    | '/medida/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  CheckoutRoute: typeof CheckoutRoute
  ContaRoute: typeof ContaRoute
  CriarContaRoute: typeof CriarContaRoute
  CronologiaRoute: typeof CronologiaRoute
  EntrarRoute: typeof EntrarRoute
  NovaRoute: typeof NovaRoute
  MedidaIdRoute: typeof MedidaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronologia': {
      id: '/cronologia'
      path: '/cronologia'
      fullPath: '/cronologia'
      preLoaderRoute: typeof CronologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova': {
      id: '/nova'
      path: '/nova'
      fullPath: '/nova'
      preLoaderRoute: typeof NovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medida/$id': {
      id: '/medida/$id'
      path: '/medida/$id'
      fullPath: '/medida/$id'
      preLoaderRoute: typeof MedidaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  CheckoutRoute: CheckoutRoute,
  ContaRoute: ContaRoute,
  CriarContaRoute: CriarContaRoute,
  CronologiaRoute: CronologiaRoute,
  EntrarRoute: EntrarRoute,
  NovaRoute: NovaRoute,
  MedidaIdRoute: MedidaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
